create table orders
(
    id           bigint generated by default as identity
        constraint orders_pkey
            primary key,
    amount       integer      not null,
    date         timestamp    not null default current_timestamp,
    product_name varchar(255) not null,
    customer_id  integer not null,
    FOREIGN KEY (customer_id) REFERENCES customers (id)
);